# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikhil Dev Deshmudre
email: nikhil.dev91 at the rate google's popular email service.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikhil-dev.github.io" # the base hostname & protocol for your site
twitter_username: theNikhilDev
github_username:  nikhil-dev

# Build settings
markdown: kramdown
